### ISSUE TITLE
大佬，请问 J-Link 固件 (ARM v8) 什么时候更新？

### ISSUE THREAD

**Issue by h2457528767** [zhangjinke/jlink_wifi_v831_hardware#1]
感谢大佬的固件，我已复刻，并成功烧录 Renesas 芯片。
希望大佬有时间能尽快更新一下 Jlink-OB arm v8 （不支持自动升级）的固件——不想每次调试都弹窗提醒升级……
感激不尽~~

**Comment by zhangjinke** [comment]
已上传

**Comment by h2457528767** [comment]
已烧录，非常好用，感谢大佬~
